### ISSUE TITLE
log.sh returns errors when run within "sudo su <someuser> -" style sub-shell

### ISSUE THREAD

**Issue by gregorydulin** [livibetter-backup/log.sh#3]
Steps to reproduce:

> \> sudo su SOMEUSER -
> \> source log.sh
> \> LSWARNING test
-bash: /dev/stdout: Permission denied

This seems to be directly related to this issue:
http://unix.stackexchange.com/questions/38538/bash-dev-stderr-permission-denied

log.sh is attempting to write to "/dev/stdout", and this fails if the current user isn't the user who owns whatever pseudoterminal /dev/stdout is symlinked to.

Per Mikel or Keith on StackExchange:

> /dev/stdout is a symlink to /proc/self/fd/1, which is a symlink to, for example, /dev/pts/1. /dev/pts/1, which is a pseudoterminal, is owned by, and writable by, username; that ownership was granted when username logged in. When you sudo su username2, the ownership of /dev/pts/1 doesn't change, and username2 doesn't have write permission.

Line 25 of log.sh is:
> LS_OUTPUT=${LS_OUTPUT:-/dev/stdout}

I tried changing that to:
> LS_OUTPUT=${LS_OUTPUT:-&1}

But that didn't work.

**Comment by gregorydulin** [comment]
I think I found a fix:

at Line 91, replace:
>echo -ne "$_LS_LEVEL_BEGIN$OUTPUT " >> "$LS_OUTPUT"
echo -n  "$_MSG"                    >> "$LS_OUTPUT"
echo -e "$_LS_LEVEL_END" >> "$LS_OUTPUT"

with
>if [ "$LS_OUTPUT" = "/dev/stdout" ]
then
echo -ne "$_LS_LEVEL_BEGIN$OUTPUT "
echo -n  "$_MSG"
echo -e "$_LS_LEVEL_END"
else
echo -ne "$_LS_LEVEL_BEGIN$OUTPUT " >> "$LS_OUTPUT"
echo -n  "$_MSG"                    >> "$LS_OUTPUT"
echo -e "$_LS_LEVEL_END" >> "$LS_OUTPUT"
fi

Once I figure out how to use github, I'll put in a patch or a merge request or make a fork or something.  (I'm still figuring out what all those words mean).

**Comment by livibetter** [comment]
Closing in favor of #5.
